server:
  port: 8080
  servlet:
    context-path: /bigdata
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/beautyfitness?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: w=8yfk@9
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:/mapper/*/*.xml
  type-aliases-package: com.big.data.bean